[build]
  command = "npm run build"
  publish = "dist/alias-gandi-angular/"
  functions = "./.netlify/functions/"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
    environment = { NODE_ENV = "development" }
