[build]
  command = "npm run build"
  publish = "dist/alias-gandi-angular/"
  functions = "./api"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
    environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
