[build]
command = "npm run build"
publish = "dist/alias-gandi-angular/"
functions = "./api"

[context.production]
environment = { NODE_ENV = "production" }

[context.deploy-preview]
environment = { NODE_ENV = "development" }

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[template.environment]
  GANDI_API_KEY = "YOUR_API_KEY"
  GANDI_API_HOST = "api.gandi.net"
  GANDI_API_VERSION = "/v5"
  JWT_SECRET = "YOUR_JWT_SECRET"
  LOGIN_PASSWORD = "YOUR_LOGIN_PASSWORD"
