@domain=bettye.net
@mailboxId=cfd66523-1846-4461-80cd-e3aa8be7b746

// @name login
POST {{host}}/auth
Content-Type: application/json

{
  "password": "{{password:}}",
  "provider": "{{provider}}"
}

###
@authToken = {{login.response.body.access_token}}

GET {{host}}/domains
Authorization: Bearer {{authToken}}

###

GET {{host}}/mailbox/{{domain}}/{{mailboxId}}
Accept: application/json
Authorization: Bearer {{authToken}}

###
POST {{host}}/aliases
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"domain": "{{domain}}",
	"mailboxId": "{{mailboxId}}",
	"aliases": []
}
